'''
8/2/2013
Sean McLaughlin
A companion file to the autogenerated preset_dialog_2
'''
from PyQt4 import QtGui, QtCore
from preset_dialog import Ui_presetDialog

if __name__ == '__main__':
    print ''' This very simple module allows the user to select a preset. The window saves the choice as a variable, and the getChoice() method returns it when called on the
    dialog's reference. 
    '''

class PresetDialog(QtGui.QDialog):#the class for the small dialog that pops up when the user wants to select a preset. 
    
    def __init__(self, presetNames, parent = None):
        super(PresetDialog, self).__init__(parent)
        self.ui = Ui_presetDialog()
        self.ui.setupUi(self)
        
        self.ui.combo_preset.addItems(presetNames)#fill the combo box
        
        self.choice = str(self.ui.combo_preset.currentText()) #get the first choice. 
        
        #signal and slot
        self.ui.combo_preset.currentIndexChanged.connect(self.change_choice)
        
    def change_choice(self):
        #when the toggle is switched, reassign the choice variable. 
        self.choice = str(self.ui.combo_preset.currentText())
        
    def getChoice(self):
        return self.choice