# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiFiles/MeasurementGUI.ui'
#
# Created: Wed Aug 14 15:53:15 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(833, 707)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.edit_dataFile = QtGui.QLineEdit(self.centralwidget)
        self.edit_dataFile.setObjectName(_fromUtf8("edit_dataFile"))
        self.horizontalLayout.addWidget(self.edit_dataFile)
        self.button_openDataFile = QtGui.QPushButton(self.centralwidget)
        self.button_openDataFile.setObjectName(_fromUtf8("button_openDataFile"))
        self.horizontalLayout.addWidget(self.button_openDataFile)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.combo_read_1 = QtGui.QComboBox(self.centralwidget)
        self.combo_read_1.setEnabled(False)
        self.combo_read_1.setObjectName(_fromUtf8("combo_read_1"))
        self.verticalLayout_2.addWidget(self.combo_read_1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_2)
        self.button_run = QtGui.QPushButton(self.centralwidget)
        self.button_run.setEnabled(False)
        self.button_run.setObjectName(_fromUtf8("button_run"))
        self.verticalLayout_12.addWidget(self.button_run)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_41.addWidget(self.label_20)
        self.label_timeEstimate = QtGui.QLabel(self.centralwidget)
        self.label_timeEstimate.setObjectName(_fromUtf8("label_timeEstimate"))
        self.horizontalLayout_41.addWidget(self.label_timeEstimate)
        self.verticalLayout_12.addLayout(self.horizontalLayout_41)
        self.button_check_run = QtGui.QPushButton(self.centralwidget)
        self.button_check_run.setEnabled(False)
        self.button_check_run.setObjectName(_fromUtf8("button_check_run"))
        self.verticalLayout_12.addWidget(self.button_check_run)
        self.button_abort = QtGui.QPushButton(self.centralwidget)
        self.button_abort.setEnabled(False)
        self.button_abort.setObjectName(_fromUtf8("button_abort"))
        self.verticalLayout_12.addWidget(self.button_abort)
        self.horizontalLayout_32.addLayout(self.verticalLayout_12)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_15.addWidget(self.line_5)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_13.addWidget(self.label_13)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_13.addWidget(self.label_12)
        self.horizontalLayout_3.addLayout(self.verticalLayout_13)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.combo_sweep1_1 = QtGui.QComboBox(self.centralwidget)
        self.combo_sweep1_1.setEnabled(False)
        self.combo_sweep1_1.setObjectName(_fromUtf8("combo_sweep1_1"))
        self.verticalLayout_3.addWidget(self.combo_sweep1_1)
        self.combo_sweep1_2 = QtGui.QComboBox(self.centralwidget)
        self.combo_sweep1_2.setEnabled(False)
        self.combo_sweep1_2.setObjectName(_fromUtf8("combo_sweep1_2"))
        self.combo_sweep1_2.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.combo_sweep1_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.edit_sweep1_start = QtGui.QLineEdit(self.centralwidget)
        self.edit_sweep1_start.setEnabled(False)
        self.edit_sweep1_start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_sweep1_start.setObjectName(_fromUtf8("edit_sweep1_start"))
        self.horizontalLayout_6.addWidget(self.edit_sweep1_start)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.edit_sweep1_end = QtGui.QLineEdit(self.centralwidget)
        self.edit_sweep1_end.setEnabled(False)
        self.edit_sweep1_end.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_sweep1_end.setObjectName(_fromUtf8("edit_sweep1_end"))
        self.horizontalLayout_7.addWidget(self.edit_sweep1_end)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_13.addWidget(self.label_17)
        self.edit_sweep1_stepSize = QtGui.QLineEdit(self.centralwidget)
        self.edit_sweep1_stepSize.setEnabled(False)
        self.edit_sweep1_stepSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_sweep1_stepSize.setObjectName(_fromUtf8("edit_sweep1_stepSize"))
        self.horizontalLayout_13.addWidget(self.edit_sweep1_stepSize)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_10.addWidget(self.label_16)
        self.edit_sweep1_dataPoints = QtGui.QLineEdit(self.centralwidget)
        self.edit_sweep1_dataPoints.setEnabled(False)
        self.edit_sweep1_dataPoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_sweep1_dataPoints.setObjectName(_fromUtf8("edit_sweep1_dataPoints"))
        self.horizontalLayout_10.addWidget(self.edit_sweep1_dataPoints)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.combo_sweep1_startUnit = QtGui.QComboBox(self.centralwidget)
        self.combo_sweep1_startUnit.setEnabled(False)
        self.combo_sweep1_startUnit.setObjectName(_fromUtf8("combo_sweep1_startUnit"))
        self.verticalLayout_6.addWidget(self.combo_sweep1_startUnit)
        self.combo_sweep1_endUnit = QtGui.QComboBox(self.centralwidget)
        self.combo_sweep1_endUnit.setEnabled(False)
        self.combo_sweep1_endUnit.setObjectName(_fromUtf8("combo_sweep1_endUnit"))
        self.verticalLayout_6.addWidget(self.combo_sweep1_endUnit)
        self.combo_sweep1_stepSizeUnit = QtGui.QComboBox(self.centralwidget)
        self.combo_sweep1_stepSizeUnit.setEnabled(False)
        self.combo_sweep1_stepSizeUnit.setObjectName(_fromUtf8("combo_sweep1_stepSizeUnit"))
        self.verticalLayout_6.addWidget(self.combo_sweep1_stepSizeUnit)
        self.check_sweep1_loop = QtGui.QCheckBox(self.centralwidget)
        self.check_sweep1_loop.setEnabled(False)
        self.check_sweep1_loop.setObjectName(_fromUtf8("check_sweep1_loop"))
        self.verticalLayout_6.addWidget(self.check_sweep1_loop)
        self.horizontalLayout_14.addLayout(self.verticalLayout_6)
        self.verticalLayout_16.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15.addLayout(self.verticalLayout_16)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_18.addWidget(self.line_4)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_14.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_14.addWidget(self.label_15)
        self.horizontalLayout_4.addLayout(self.verticalLayout_14)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.combo_sweep2_1 = QtGui.QComboBox(self.centralwidget)
        self.combo_sweep2_1.setEnabled(False)
        self.combo_sweep2_1.setObjectName(_fromUtf8("combo_sweep2_1"))
        self.combo_sweep2_1.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.combo_sweep2_1)
        self.combo_sweep2_2 = QtGui.QComboBox(self.centralwidget)
        self.combo_sweep2_2.setEnabled(False)
        self.combo_sweep2_2.setObjectName(_fromUtf8("combo_sweep2_2"))
        self.combo_sweep2_2.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.combo_sweep2_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_17.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.edit_sweep2_start = QtGui.QLineEdit(self.centralwidget)
        self.edit_sweep2_start.setEnabled(False)
        self.edit_sweep2_start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_sweep2_start.setObjectName(_fromUtf8("edit_sweep2_start"))
        self.horizontalLayout_8.addWidget(self.edit_sweep2_start)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_9.addWidget(self.label_8)
        self.edit_sweep2_end = QtGui.QLineEdit(self.centralwidget)
        self.edit_sweep2_end.setEnabled(False)
        self.edit_sweep2_end.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_sweep2_end.setObjectName(_fromUtf8("edit_sweep2_end"))
        self.horizontalLayout_9.addWidget(self.edit_sweep2_end)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_16.addWidget(self.label_24)
        self.edit_sweep2_stepSize = QtGui.QLineEdit(self.centralwidget)
        self.edit_sweep2_stepSize.setEnabled(False)
        self.edit_sweep2_stepSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_sweep2_stepSize.setObjectName(_fromUtf8("edit_sweep2_stepSize"))
        self.horizontalLayout_16.addWidget(self.edit_sweep2_stepSize)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_28.addWidget(self.label_23)
        self.edit_sweep2_dataPoints = QtGui.QLineEdit(self.centralwidget)
        self.edit_sweep2_dataPoints.setEnabled(False)
        self.edit_sweep2_dataPoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_sweep2_dataPoints.setObjectName(_fromUtf8("edit_sweep2_dataPoints"))
        self.horizontalLayout_28.addWidget(self.edit_sweep2_dataPoints)
        self.verticalLayout_9.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_17.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.combo_sweep2_startUnit = QtGui.QComboBox(self.centralwidget)
        self.combo_sweep2_startUnit.setEnabled(False)
        self.combo_sweep2_startUnit.setObjectName(_fromUtf8("combo_sweep2_startUnit"))
        self.verticalLayout_8.addWidget(self.combo_sweep2_startUnit)
        self.combo_sweep2_endUnit = QtGui.QComboBox(self.centralwidget)
        self.combo_sweep2_endUnit.setEnabled(False)
        self.combo_sweep2_endUnit.setObjectName(_fromUtf8("combo_sweep2_endUnit"))
        self.verticalLayout_8.addWidget(self.combo_sweep2_endUnit)
        self.combo_sweep2_stepSizeUnit = QtGui.QComboBox(self.centralwidget)
        self.combo_sweep2_stepSizeUnit.setEnabled(False)
        self.combo_sweep2_stepSizeUnit.setObjectName(_fromUtf8("combo_sweep2_stepSizeUnit"))
        self.verticalLayout_8.addWidget(self.combo_sweep2_stepSizeUnit)
        self.check_sweep2_loop = QtGui.QCheckBox(self.centralwidget)
        self.check_sweep2_loop.setEnabled(False)
        self.check_sweep2_loop.setObjectName(_fromUtf8("check_sweep2_loop"))
        self.verticalLayout_8.addWidget(self.check_sweep2_loop)
        self.horizontalLayout_17.addLayout(self.verticalLayout_8)
        self.verticalLayout_17.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18.addLayout(self.verticalLayout_17)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout_31.addWidget(self.line_7)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_15.addWidget(self.label_27)
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_15.addWidget(self.label_28)
        self.horizontalLayout_5.addLayout(self.verticalLayout_15)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.combo_sweep3_1 = QtGui.QComboBox(self.centralwidget)
        self.combo_sweep3_1.setEnabled(False)
        self.combo_sweep3_1.setObjectName(_fromUtf8("combo_sweep3_1"))
        self.combo_sweep3_1.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.combo_sweep3_1)
        self.combo_sweep3_2 = QtGui.QComboBox(self.centralwidget)
        self.combo_sweep3_2.setEnabled(False)
        self.combo_sweep3_2.setObjectName(_fromUtf8("combo_sweep3_2"))
        self.combo_sweep3_2.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.combo_sweep3_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_18.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_11.addWidget(self.label_10)
        self.edit_sweep3_start = QtGui.QLineEdit(self.centralwidget)
        self.edit_sweep3_start.setEnabled(False)
        self.edit_sweep3_start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_sweep3_start.setObjectName(_fromUtf8("edit_sweep3_start"))
        self.horizontalLayout_11.addWidget(self.edit_sweep3_start)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_12.addWidget(self.label_11)
        self.edit_sweep3_end = QtGui.QLineEdit(self.centralwidget)
        self.edit_sweep3_end.setEnabled(False)
        self.edit_sweep3_end.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_sweep3_end.setObjectName(_fromUtf8("edit_sweep3_end"))
        self.horizontalLayout_12.addWidget(self.edit_sweep3_end)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_19.addWidget(self.label_26)
        self.edit_sweep3_stepSize = QtGui.QLineEdit(self.centralwidget)
        self.edit_sweep3_stepSize.setEnabled(False)
        self.edit_sweep3_stepSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_sweep3_stepSize.setObjectName(_fromUtf8("edit_sweep3_stepSize"))
        self.horizontalLayout_19.addWidget(self.edit_sweep3_stepSize)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_29.addWidget(self.label_25)
        self.edit_sweep3_dataPoints = QtGui.QLineEdit(self.centralwidget)
        self.edit_sweep3_dataPoints.setEnabled(False)
        self.edit_sweep3_dataPoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_sweep3_dataPoints.setObjectName(_fromUtf8("edit_sweep3_dataPoints"))
        self.horizontalLayout_29.addWidget(self.edit_sweep3_dataPoints)
        self.verticalLayout_10.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.combo_sweep3_startUnit = QtGui.QComboBox(self.centralwidget)
        self.combo_sweep3_startUnit.setEnabled(False)
        self.combo_sweep3_startUnit.setObjectName(_fromUtf8("combo_sweep3_startUnit"))
        self.verticalLayout_11.addWidget(self.combo_sweep3_startUnit)
        self.combo_sweep3_endUnit = QtGui.QComboBox(self.centralwidget)
        self.combo_sweep3_endUnit.setEnabled(False)
        self.combo_sweep3_endUnit.setObjectName(_fromUtf8("combo_sweep3_endUnit"))
        self.verticalLayout_11.addWidget(self.combo_sweep3_endUnit)
        self.combo_sweep3_stepSizeUnit = QtGui.QComboBox(self.centralwidget)
        self.combo_sweep3_stepSizeUnit.setEnabled(False)
        self.combo_sweep3_stepSizeUnit.setObjectName(_fromUtf8("combo_sweep3_stepSizeUnit"))
        self.verticalLayout_11.addWidget(self.combo_sweep3_stepSizeUnit)
        self.check_sweep3_loop = QtGui.QCheckBox(self.centralwidget)
        self.check_sweep3_loop.setEnabled(False)
        self.check_sweep3_loop.setObjectName(_fromUtf8("check_sweep3_loop"))
        self.verticalLayout_11.addWidget(self.check_sweep3_loop)
        self.horizontalLayout_30.addLayout(self.verticalLayout_11)
        self.verticalLayout_18.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31.addLayout(self.verticalLayout_18)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_31)
        self.gridLayout.addLayout(self.horizontalLayout_32, 1, 0, 1, 1)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout.addWidget(self.line_6, 2, 0, 1, 1)
        self.pqlayout = LayoutWidget(self.centralwidget)
        self.pqlayout.setEnabled(True)
        self.pqlayout.setMinimumSize(QtCore.QSize(425, 250))
        self.pqlayout.setObjectName(_fromUtf8("pqlayout"))
        self.gridLayout.addWidget(self.pqlayout, 3, 0, 1, 1)
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_24.setMargin(0)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_32 = QtGui.QLabel(self.widget)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_35.addWidget(self.label_32)
        self.label_sweep1 = QtGui.QLabel(self.widget)
        self.label_sweep1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sweep1.setObjectName(_fromUtf8("label_sweep1"))
        self.horizontalLayout_35.addWidget(self.label_sweep1)
        self.verticalLayout_21.addLayout(self.horizontalLayout_35)
        self.progressBar_1 = QtGui.QProgressBar(self.widget)
        self.progressBar_1.setProperty("value", 0)
        self.progressBar_1.setTextVisible(False)
        self.progressBar_1.setObjectName(_fromUtf8("progressBar_1"))
        self.verticalLayout_21.addWidget(self.progressBar_1)
        self.verticalLayout_24.addLayout(self.verticalLayout_21)
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.edit_slice1 = QtGui.QLineEdit(self.widget)
        self.edit_slice1.setEnabled(False)
        self.edit_slice1.setObjectName(_fromUtf8("edit_slice1"))
        self.horizontalLayout_42.addWidget(self.edit_slice1)
        self.combo_slice1 = QtGui.QComboBox(self.widget)
        self.combo_slice1.setEnabled(False)
        self.combo_slice1.setObjectName(_fromUtf8("combo_slice1"))
        self.horizontalLayout_42.addWidget(self.combo_slice1)
        self.check_sweep1_slice = QtGui.QCheckBox(self.widget)
        self.check_sweep1_slice.setChecked(True)
        self.check_sweep1_slice.setObjectName(_fromUtf8("check_sweep1_slice"))
        self.horizontalLayout_42.addWidget(self.check_sweep1_slice)
        self.verticalLayout_24.addLayout(self.horizontalLayout_42)
        self.widget1 = QtGui.QWidget(self.splitter)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_25.setMargin(0)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.label_33 = QtGui.QLabel(self.widget1)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_36.addWidget(self.label_33)
        self.label_sweep2 = QtGui.QLabel(self.widget1)
        self.label_sweep2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sweep2.setObjectName(_fromUtf8("label_sweep2"))
        self.horizontalLayout_36.addWidget(self.label_sweep2)
        self.verticalLayout_22.addLayout(self.horizontalLayout_36)
        self.progressBar_2 = QtGui.QProgressBar(self.widget1)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.verticalLayout_22.addWidget(self.progressBar_2)
        self.verticalLayout_25.addLayout(self.verticalLayout_22)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.edit_slice2 = QtGui.QLineEdit(self.widget1)
        self.edit_slice2.setEnabled(False)
        self.edit_slice2.setObjectName(_fromUtf8("edit_slice2"))
        self.horizontalLayout_43.addWidget(self.edit_slice2)
        self.combo_slice2 = QtGui.QComboBox(self.widget1)
        self.combo_slice2.setEnabled(False)
        self.combo_slice2.setObjectName(_fromUtf8("combo_slice2"))
        self.horizontalLayout_43.addWidget(self.combo_slice2)
        self.check_sweep2_slice = QtGui.QCheckBox(self.widget1)
        self.check_sweep2_slice.setChecked(True)
        self.check_sweep2_slice.setObjectName(_fromUtf8("check_sweep2_slice"))
        self.horizontalLayout_43.addWidget(self.check_sweep2_slice)
        self.verticalLayout_25.addLayout(self.horizontalLayout_43)
        self.widget2 = QtGui.QWidget(self.splitter)
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_26.setMargin(0)
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_34 = QtGui.QLabel(self.widget2)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_37.addWidget(self.label_34)
        self.label_sweep3 = QtGui.QLabel(self.widget2)
        self.label_sweep3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sweep3.setObjectName(_fromUtf8("label_sweep3"))
        self.horizontalLayout_37.addWidget(self.label_sweep3)
        self.verticalLayout_23.addLayout(self.horizontalLayout_37)
        self.progressBar_3 = QtGui.QProgressBar(self.widget2)
        self.progressBar_3.setMinimum(0)
        self.progressBar_3.setMaximum(100)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setTextVisible(False)
        self.progressBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_3.setInvertedAppearance(False)
        self.progressBar_3.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.verticalLayout_23.addWidget(self.progressBar_3)
        self.verticalLayout_26.addLayout(self.verticalLayout_23)
        self.horizontalLayout_44 = QtGui.QHBoxLayout()
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        self.edit_slice3 = QtGui.QLineEdit(self.widget2)
        self.edit_slice3.setEnabled(False)
        self.edit_slice3.setObjectName(_fromUtf8("edit_slice3"))
        self.horizontalLayout_44.addWidget(self.edit_slice3)
        self.combo_slice3 = QtGui.QComboBox(self.widget2)
        self.combo_slice3.setEnabled(False)
        self.combo_slice3.setObjectName(_fromUtf8("combo_slice3"))
        self.horizontalLayout_44.addWidget(self.combo_slice3)
        self.check_sweep3_slice = QtGui.QCheckBox(self.widget2)
        self.check_sweep3_slice.setChecked(True)
        self.check_sweep3_slice.setObjectName(_fromUtf8("check_sweep3_slice"))
        self.horizontalLayout_44.addWidget(self.check_sweep3_slice)
        self.verticalLayout_26.addLayout(self.horizontalLayout_44)
        self.verticalLayout_27.addWidget(self.splitter)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_27.addWidget(self.line_3)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_19.addWidget(self.label_21)
        self.combo_plotType = QtGui.QComboBox(self.centralwidget)
        self.combo_plotType.setEnabled(False)
        self.combo_plotType.setObjectName(_fromUtf8("combo_plotType"))
        self.combo_plotType.addItem(_fromUtf8(""))
        self.combo_plotType.addItem(_fromUtf8(""))
        self.verticalLayout_19.addWidget(self.combo_plotType)
        self.button_refresh_plot = QtGui.QPushButton(self.centralwidget)
        self.button_refresh_plot.setEnabled(False)
        self.button_refresh_plot.setObjectName(_fromUtf8("button_refresh_plot"))
        self.verticalLayout_19.addWidget(self.button_refresh_plot)
        self.horizontalLayout_40.addLayout(self.verticalLayout_19)
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout_40.addWidget(self.line_8)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_20.addWidget(self.label_18)
        self.combo_xScale = QtGui.QComboBox(self.centralwidget)
        self.combo_xScale.setEnabled(False)
        self.combo_xScale.setObjectName(_fromUtf8("combo_xScale"))
        self.combo_xScale.addItem(_fromUtf8(""))
        self.combo_xScale.addItem(_fromUtf8(""))
        self.horizontalLayout_20.addWidget(self.combo_xScale)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_25.addWidget(self.label_22)
        self.combo_yScale = QtGui.QComboBox(self.centralwidget)
        self.combo_yScale.setEnabled(False)
        self.combo_yScale.setObjectName(_fromUtf8("combo_yScale"))
        self.combo_yScale.addItem(_fromUtf8(""))
        self.combo_yScale.addItem(_fromUtf8(""))
        self.horizontalLayout_25.addWidget(self.combo_yScale)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_25.addWidget(self.line_2)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_21.addWidget(self.label_19)
        self.combo_xAxis = QtGui.QComboBox(self.centralwidget)
        self.combo_xAxis.setEnabled(False)
        self.combo_xAxis.setObjectName(_fromUtf8("combo_xAxis"))
        self.horizontalLayout_21.addWidget(self.combo_xAxis)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_24)
        self.verticalLayout_20.addLayout(self.horizontalLayout_27)
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.verticalLayout_20.addWidget(self.line_10)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_33.addWidget(self.label_30)
        self.combo_image_x = QtGui.QComboBox(self.centralwidget)
        self.combo_image_x.setEnabled(False)
        self.combo_image_x.setObjectName(_fromUtf8("combo_image_x"))
        self.horizontalLayout_33.addWidget(self.combo_image_x)
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_33.addWidget(self.label_31)
        self.combo_image_y = QtGui.QComboBox(self.centralwidget)
        self.combo_image_y.setEnabled(False)
        self.combo_image_y.setObjectName(_fromUtf8("combo_image_y"))
        self.horizontalLayout_33.addWidget(self.combo_image_y)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_35 = QtGui.QLabel(self.centralwidget)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_34.addWidget(self.label_35)
        self.combo_image_z = QtGui.QComboBox(self.centralwidget)
        self.combo_image_z.setEnabled(False)
        self.combo_image_z.setObjectName(_fromUtf8("combo_image_z"))
        self.horizontalLayout_34.addWidget(self.combo_image_z)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_34)
        self.verticalLayout_20.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40.addLayout(self.verticalLayout_20)
        self.verticalLayout_27.addLayout(self.horizontalLayout_40)
        self.gridLayout.addLayout(self.verticalLayout_27, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_GASconfig = QtGui.QMenu(self.menubar)
        self.menu_GASconfig.setObjectName(_fromUtf8("menu_GASconfig"))
        self.menu_INSTconfig = QtGui.QMenu(self.menubar)
        self.menu_INSTconfig.setObjectName(_fromUtf8("menu_INSTconfig"))
        self.menu_Presets = QtGui.QMenu(self.menubar)
        self.menu_Presets.setObjectName(_fromUtf8("menu_Presets"))
        self.menu_Calibrate = QtGui.QMenu(self.menubar)
        self.menu_Calibrate.setObjectName(_fromUtf8("menu_Calibrate"))
        MainWindow.setMenuBar(self.menubar)
        self.action_Open_GASFile = QtGui.QAction(MainWindow)
        self.action_Open_GASFile.setObjectName(_fromUtf8("action_Open_GASFile"))
        self.actionOpen_GASEdit = QtGui.QAction(MainWindow)
        self.actionOpen_GASEdit.setObjectName(_fromUtf8("actionOpen_GASEdit"))
        self.actionOpen_INSTEdit = QtGui.QAction(MainWindow)
        self.actionOpen_INSTEdit.setObjectName(_fromUtf8("actionOpen_INSTEdit"))
        self.actionPreset_1 = QtGui.QAction(MainWindow)
        self.actionPreset_1.setObjectName(_fromUtf8("actionPreset_1"))
        self.action_Calibrate_B_Field = QtGui.QAction(MainWindow)
        self.action_Calibrate_B_Field.setEnabled(False)
        self.action_Calibrate_B_Field.setObjectName(_fromUtf8("action_Calibrate_B_Field"))
        self.action_Get_Background_Subtract = QtGui.QAction(MainWindow)
        self.action_Get_Background_Subtract.setEnabled(False)
        self.action_Get_Background_Subtract.setObjectName(_fromUtf8("action_Get_Background_Subtract"))
        self.action_Save_as_Preset = QtGui.QAction(MainWindow)
        self.action_Save_as_Preset.setObjectName(_fromUtf8("action_Save_as_Preset"))
        self.actionEdit_Delete_Presets = QtGui.QAction(MainWindow)
        self.actionEdit_Delete_Presets.setObjectName(_fromUtf8("actionEdit_Delete_Presets"))
        self.action_Open_Preset = QtGui.QAction(MainWindow)
        self.action_Open_Preset.setObjectName(_fromUtf8("action_Open_Preset"))
        self.action_Set_Microwave_Amplitude = QtGui.QAction(MainWindow)
        self.action_Set_Microwave_Amplitude.setObjectName(_fromUtf8("action_Set_Microwave_Amplitude"))
        self.menu_GASconfig.addAction(self.action_Open_GASFile)
        self.menu_GASconfig.addAction(self.actionOpen_GASEdit)
        self.menu_INSTconfig.addAction(self.actionOpen_INSTEdit)
        self.menu_Presets.addAction(self.action_Open_Preset)
        self.menu_Presets.addSeparator()
        self.menu_Presets.addAction(self.action_Save_as_Preset)
        self.menu_Presets.addAction(self.actionEdit_Delete_Presets)
        self.menu_Calibrate.addAction(self.action_Calibrate_B_Field)
        self.menu_Calibrate.addAction(self.action_Get_Background_Subtract)
        self.menu_Calibrate.addAction(self.action_Set_Microwave_Amplitude)
        self.menubar.addAction(self.menu_GASconfig.menuAction())
        self.menubar.addAction(self.menu_INSTconfig.menuAction())
        self.menubar.addAction(self.menu_Calibrate.menuAction())
        self.menubar.addAction(self.menu_Presets.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.combo_sweep1_startUnit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.combo_sweep1_endUnit.setCurrentIndex)
        QtCore.QObject.connect(self.combo_sweep1_endUnit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.combo_sweep1_startUnit.setCurrentIndex)
        QtCore.QObject.connect(self.combo_sweep1_startUnit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.combo_sweep1_stepSizeUnit.setCurrentIndex)
        QtCore.QObject.connect(self.combo_sweep1_endUnit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.combo_sweep1_stepSizeUnit.setCurrentIndex)
        QtCore.QObject.connect(self.combo_sweep2_startUnit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.combo_sweep2_endUnit.setCurrentIndex)
        QtCore.QObject.connect(self.combo_sweep2_endUnit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.combo_sweep2_startUnit.setCurrentIndex)
        QtCore.QObject.connect(self.combo_sweep2_startUnit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.combo_sweep2_stepSizeUnit.setCurrentIndex)
        QtCore.QObject.connect(self.combo_sweep2_endUnit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.combo_sweep2_stepSizeUnit.setCurrentIndex)
        QtCore.QObject.connect(self.combo_sweep3_startUnit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.combo_sweep3_endUnit.setCurrentIndex)
        QtCore.QObject.connect(self.combo_sweep3_endUnit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.combo_sweep3_startUnit.setCurrentIndex)
        QtCore.QObject.connect(self.combo_sweep3_endUnit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.combo_sweep3_stepSizeUnit.setCurrentIndex)
        QtCore.QObject.connect(self.combo_sweep3_startUnit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.combo_sweep3_stepSizeUnit.setCurrentIndex)
        QtCore.QObject.connect(self.check_sweep1_slice, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.combo_slice1.setDisabled)
        QtCore.QObject.connect(self.check_sweep1_slice, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edit_slice1.setDisabled)
        QtCore.QObject.connect(self.check_sweep2_slice, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.combo_slice2.setDisabled)
        QtCore.QObject.connect(self.check_sweep2_slice, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edit_slice2.setDisabled)
        QtCore.QObject.connect(self.check_sweep3_slice, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.combo_slice3.setDisabled)
        QtCore.QObject.connect(self.check_sweep3_slice, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.edit_slice3.setDisabled)
        QtCore.QObject.connect(self.combo_sweep1_startUnit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.combo_slice1.setCurrentIndex)
        QtCore.QObject.connect(self.combo_sweep2_startUnit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.combo_slice2.setCurrentIndex)
        QtCore.QObject.connect(self.combo_sweep3_startUnit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.combo_slice3.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Data File", None))
        self.button_openDataFile.setText(_translate("MainWindow", "Save As", None))
        self.label_2.setText(_translate("MainWindow", "Read", None))
        self.button_run.setText(_translate("MainWindow", "Run", None))
        self.label_20.setText(_translate("MainWindow", "Estimated Time", None))
        self.label_timeEstimate.setText(_translate("MainWindow", "0h0m0s", None))
        self.button_check_run.setText(_translate("MainWindow", "Check Run", None))
        self.button_abort.setText(_translate("MainWindow", "Abort", None))
        self.label_3.setText(_translate("MainWindow", "Sweep 1", None))
        self.label_13.setText(_translate("MainWindow", "Set", None))
        self.label_12.setText(_translate("MainWindow", "Read", None))
        self.combo_sweep1_2.setItemText(0, _translate("MainWindow", "Set Point", None))
        self.label_5.setText(_translate("MainWindow", "Sweep 1 Start", None))
        self.label_6.setText(_translate("MainWindow", "Sweep 1 End", None))
        self.label_17.setText(_translate("MainWindow", "Step Size", None))
        self.label_16.setText(_translate("MainWindow", "Data Points", None))
        self.check_sweep1_loop.setText(_translate("MainWindow", "Loop", None))
        self.label_4.setText(_translate("MainWindow", "Sweep 2", None))
        self.label_14.setText(_translate("MainWindow", "Set", None))
        self.label_15.setText(_translate("MainWindow", "Read", None))
        self.combo_sweep2_1.setItemText(0, _translate("MainWindow", "None", None))
        self.combo_sweep2_2.setItemText(0, _translate("MainWindow", "Set Point", None))
        self.label_7.setText(_translate("MainWindow", "Sweep 2 Start", None))
        self.label_8.setText(_translate("MainWindow", "Sweep 2 End", None))
        self.label_24.setText(_translate("MainWindow", "Step Size", None))
        self.label_23.setText(_translate("MainWindow", "Data Points", None))
        self.check_sweep2_loop.setText(_translate("MainWindow", "Loop", None))
        self.label_9.setText(_translate("MainWindow", "Sweep 3", None))
        self.label_27.setText(_translate("MainWindow", "Set", None))
        self.label_28.setText(_translate("MainWindow", "Read", None))
        self.combo_sweep3_1.setItemText(0, _translate("MainWindow", "None", None))
        self.combo_sweep3_2.setItemText(0, _translate("MainWindow", "Set Point", None))
        self.label_10.setText(_translate("MainWindow", "Sweep 3 Start", None))
        self.label_11.setText(_translate("MainWindow", "Sweep 3 End", None))
        self.label_26.setText(_translate("MainWindow", "Step Size", None))
        self.label_25.setText(_translate("MainWindow", "Data Points", None))
        self.check_sweep3_loop.setText(_translate("MainWindow", "Loop", None))
        self.label_32.setText(_translate("MainWindow", "Sweep 1", None))
        self.label_sweep1.setText(_translate("MainWindow", "0", None))
        self.check_sweep1_slice.setText(_translate("MainWindow", "All", None))
        self.label_33.setText(_translate("MainWindow", "Sweep 2", None))
        self.label_sweep2.setText(_translate("MainWindow", "0", None))
        self.progressBar_2.setFormat(_translate("MainWindow", "%v", None))
        self.check_sweep2_slice.setText(_translate("MainWindow", "All", None))
        self.label_34.setText(_translate("MainWindow", "Sweep 3", None))
        self.label_sweep3.setText(_translate("MainWindow", "0", None))
        self.progressBar_3.setFormat(_translate("MainWindow", "%v", None))
        self.check_sweep3_slice.setText(_translate("MainWindow", "All", None))
        self.label_21.setText(_translate("MainWindow", "Plot Type", None))
        self.combo_plotType.setItemText(0, _translate("MainWindow", "Line", None))
        self.combo_plotType.setItemText(1, _translate("MainWindow", "Image", None))
        self.button_refresh_plot.setText(_translate("MainWindow", "Refresh Plot", None))
        self.label_18.setText(_translate("MainWindow", "X Scale", None))
        self.combo_xScale.setItemText(0, _translate("MainWindow", "Linear", None))
        self.combo_xScale.setItemText(1, _translate("MainWindow", "Log", None))
        self.label_22.setText(_translate("MainWindow", "Y Scale", None))
        self.combo_yScale.setItemText(0, _translate("MainWindow", "Linear", None))
        self.combo_yScale.setItemText(1, _translate("MainWindow", "Log", None))
        self.label_19.setText(_translate("MainWindow", "X- Axis", None))
        self.label_30.setText(_translate("MainWindow", "X-Axis", None))
        self.label_31.setText(_translate("MainWindow", "Y-Axis", None))
        self.label_35.setText(_translate("MainWindow", "Z-Axis (Color)", None))
        self.menu_GASconfig.setTitle(_translate("MainWindow", "&GASconfig", None))
        self.menu_INSTconfig.setTitle(_translate("MainWindow", "&INSTconfig", None))
        self.menu_Presets.setTitle(_translate("MainWindow", "&Presets", None))
        self.menu_Calibrate.setTitle(_translate("MainWindow", "&Calibrate", None))
        self.action_Open_GASFile.setText(_translate("MainWindow", "&Open File", None))
        self.actionOpen_GASEdit.setText(_translate("MainWindow", "Open Edit", None))
        self.actionOpen_INSTEdit.setText(_translate("MainWindow", "Open Edit", None))
        self.actionPreset_1.setText(_translate("MainWindow", "Preset_1", None))
        self.action_Calibrate_B_Field.setText(_translate("MainWindow", "&Calibrate B-Field", None))
        self.action_Get_Background_Subtract.setText(_translate("MainWindow", "&Get Background Subtract", None))
        self.action_Save_as_Preset.setText(_translate("MainWindow", "&Save as Preset", None))
        self.actionEdit_Delete_Presets.setText(_translate("MainWindow", "&Delete Presets", None))
        self.action_Open_Preset.setText(_translate("MainWindow", "&Open Preset", None))
        self.action_Set_Microwave_Amplitude.setText(_translate("MainWindow", "&Set Microwave Amplitude", None))

from pyqtgraph import LayoutWidget
