# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiFiles/GASconfig_window_add.ui'
#
# Created: Thu Aug 15 12:06:54 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_window_add(object):
    def setupUi(self, window_add):
        window_add.setObjectName(_fromUtf8("window_add"))
        window_add.setWindowModality(QtCore.Qt.WindowModal)
        window_add.resize(438, 355)
        self.gridLayout = QtGui.QGridLayout(window_add)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(window_add)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.edit_name = QtGui.QLineEdit(window_add)
        self.edit_name.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.edit_name.setObjectName(_fromUtf8("edit_name"))
        self.horizontalLayout.addWidget(self.edit_name)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(window_add)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.combo_classType = QtGui.QComboBox(window_add)
        self.combo_classType.setObjectName(_fromUtf8("combo_classType"))
        self.horizontalLayout_2.addWidget(self.combo_classType)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(window_add)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.combo_instrumentType = QtGui.QComboBox(window_add)
        self.combo_instrumentType.setObjectName(_fromUtf8("combo_instrumentType"))
        self.horizontalLayout_3.addWidget(self.combo_instrumentType)
        self.label_4 = QtGui.QLabel(window_add)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.edit_address = QtGui.QLineEdit(window_add)
        self.edit_address.setEnabled(False)
        self.edit_address.setObjectName(_fromUtf8("edit_address"))
        self.horizontalLayout_3.addWidget(self.edit_address)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(window_add)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.edit_delay = QtGui.QLineEdit(window_add)
        self.edit_delay.setObjectName(_fromUtf8("edit_delay"))
        self.horizontalLayout_8.addWidget(self.edit_delay)
        self.combo_delay = QtGui.QComboBox(window_add)
        self.combo_delay.setObjectName(_fromUtf8("combo_delay"))
        self.combo_delay.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.combo_delay)
        self.gridLayout.addLayout(self.horizontalLayout_8, 3, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(window_add)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.edit_delay_2 = QtGui.QLineEdit(window_add)
        self.edit_delay_2.setEnabled(False)
        self.edit_delay_2.setObjectName(_fromUtf8("edit_delay_2"))
        self.horizontalLayout_9.addWidget(self.edit_delay_2)
        self.combo_delay_2 = QtGui.QComboBox(window_add)
        self.combo_delay_2.setEnabled(False)
        self.combo_delay_2.setObjectName(_fromUtf8("combo_delay_2"))
        self.combo_delay_2.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.combo_delay_2)
        self.gridLayout.addLayout(self.horizontalLayout_9, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(window_add)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.combo_measurementType = QtGui.QComboBox(window_add)
        self.combo_measurementType.setEnabled(False)
        self.combo_measurementType.setObjectName(_fromUtf8("combo_measurementType"))
        self.horizontalLayout_4.addWidget(self.combo_measurementType)
        self.label_6 = QtGui.QLabel(window_add)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.spin_port = QtGui.QSpinBox(window_add)
        self.spin_port.setEnabled(False)
        self.spin_port.setMinimum(1)
        self.spin_port.setMaximum(4)
        self.spin_port.setObjectName(_fromUtf8("spin_port"))
        self.horizontalLayout_4.addWidget(self.spin_port)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(window_add)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.edit_OCR = QtGui.QLineEdit(window_add)
        self.edit_OCR.setObjectName(_fromUtf8("edit_OCR"))
        self.horizontalLayout_6.addWidget(self.edit_OCR)
        self.gridLayout.addLayout(self.horizontalLayout_6, 6, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_11 = QtGui.QLabel(window_add)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        self.combo_current = QtGui.QComboBox(window_add)
        self.combo_current.setEnabled(False)
        self.combo_current.setObjectName(_fromUtf8("combo_current"))
        self.horizontalLayout_10.addWidget(self.combo_current)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_12 = QtGui.QLabel(window_add)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_11.addWidget(self.label_12)
        self.combo_Voltage = QtGui.QComboBox(window_add)
        self.combo_Voltage.setEnabled(False)
        self.combo_Voltage.setObjectName(_fromUtf8("combo_Voltage"))
        self.horizontalLayout_11.addWidget(self.combo_Voltage)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.gridLayout.addLayout(self.horizontalLayout_12, 7, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_13 = QtGui.QLabel(window_add)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_13.addWidget(self.label_13)
        self.edit_amplitude = QtGui.QLineEdit(window_add)
        self.edit_amplitude.setEnabled(False)
        self.edit_amplitude.setObjectName(_fromUtf8("edit_amplitude"))
        self.horizontalLayout_13.addWidget(self.edit_amplitude)
        self.combo_amplitude = QtGui.QComboBox(window_add)
        self.combo_amplitude.setEnabled(False)
        self.combo_amplitude.setObjectName(_fromUtf8("combo_amplitude"))
        self.combo_amplitude.addItem(_fromUtf8(""))
        self.combo_amplitude.addItem(_fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.combo_amplitude)
        self.gridLayout.addLayout(self.horizontalLayout_13, 8, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_8 = QtGui.QLabel(window_add)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_7.addWidget(self.label_8)
        self.edit_comment = QtGui.QLineEdit(window_add)
        self.edit_comment.setEnabled(True)
        self.edit_comment.setObjectName(_fromUtf8("edit_comment"))
        self.horizontalLayout_7.addWidget(self.edit_comment)
        self.gridLayout.addLayout(self.horizontalLayout_7, 9, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.button_add = QtGui.QPushButton(window_add)
        self.button_add.setEnabled(False)
        self.button_add.setObjectName(_fromUtf8("button_add"))
        self.horizontalLayout_5.addWidget(self.button_add)
        self.button_cancel = QtGui.QPushButton(window_add)
        self.button_cancel.setObjectName(_fromUtf8("button_cancel"))
        self.horizontalLayout_5.addWidget(self.button_cancel)
        self.gridLayout.addLayout(self.horizontalLayout_5, 10, 0, 1, 1)

        self.retranslateUi(window_add)
        QtCore.QObject.connect(self.button_cancel, QtCore.SIGNAL(_fromUtf8("clicked()")), window_add.close)
        QtCore.QMetaObject.connectSlotsByName(window_add)

    def retranslateUi(self, window_add):
        window_add.setWindowTitle(_translate("window_add", "GAS Add", None))
        self.label.setText(_translate("window_add", "Name", None))
        self.label_2.setText(_translate("window_add", "Class Type", None))
        self.label_3.setText(_translate("window_add", "Instrument Type", None))
        self.label_4.setText(_translate("window_add", "Address", None))
        self.label_9.setText(_translate("window_add", "Delay", None))
        self.combo_delay.setItemText(0, _translate("window_add", "Seconds", None))
        self.label_10.setText(_translate("window_add", "Delay 2 ", None))
        self.combo_delay_2.setItemText(0, _translate("window_add", "Seconds", None))
        self.label_5.setText(_translate("window_add", "Measurement Type", None))
        self.label_6.setText(_translate("window_add", "Port", None))
        self.label_7.setText(_translate("window_add", "OCR Calibration (A)", None))
        self.label_11.setText(_translate("window_add", "getCurrent", None))
        self.label_12.setText(_translate("window_add", "getVoltage", None))
        self.label_13.setText(_translate("window_add", "Amplitude", None))
        self.combo_amplitude.setItemText(0, _translate("window_add", "mV", None))
        self.combo_amplitude.setItemText(1, _translate("window_add", "dBm", None))
        self.label_8.setText(_translate("window_add", "Comment:", None))
        self.button_add.setText(_translate("window_add", "Add", None))
        self.button_cancel.setText(_translate("window_add", "Cancel", None))

