# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiFiles/GASconfig_window_edit.ui'
#
# Created: Thu Aug 15 12:05:55 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(369, 362)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        self.edit_delay = QtGui.QLineEdit(Form)
        self.edit_delay.setObjectName(_fromUtf8("edit_delay"))
        self.horizontalLayout_10.addWidget(self.edit_delay)
        self.combo_delay = QtGui.QComboBox(Form)
        self.combo_delay.setObjectName(_fromUtf8("combo_delay"))
        self.combo_delay.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.combo_delay)
        self.gridLayout.addLayout(self.horizontalLayout_10, 5, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_13 = QtGui.QLabel(Form)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_14.addWidget(self.label_13)
        self.combo_current = QtGui.QComboBox(Form)
        self.combo_current.setEnabled(False)
        self.combo_current.setObjectName(_fromUtf8("combo_current"))
        self.horizontalLayout_14.addWidget(self.combo_current)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_14 = QtGui.QLabel(Form)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_15.addWidget(self.label_14)
        self.combo_Voltage = QtGui.QComboBox(Form)
        self.combo_Voltage.setEnabled(False)
        self.combo_Voltage.setObjectName(_fromUtf8("combo_Voltage"))
        self.horizontalLayout_15.addWidget(self.combo_Voltage)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_15)
        self.gridLayout.addLayout(self.horizontalLayout_13, 9, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_11.addWidget(self.label_12)
        self.edit_delay_2 = QtGui.QLineEdit(Form)
        self.edit_delay_2.setEnabled(False)
        self.edit_delay_2.setObjectName(_fromUtf8("edit_delay_2"))
        self.horizontalLayout_11.addWidget(self.edit_delay_2)
        self.combo_delay_2 = QtGui.QComboBox(Form)
        self.combo_delay_2.setEnabled(False)
        self.combo_delay_2.setObjectName(_fromUtf8("combo_delay_2"))
        self.combo_delay_2.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.combo_delay_2)
        self.gridLayout.addLayout(self.horizontalLayout_11, 6, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.edit_OCR = QtGui.QLineEdit(Form)
        self.edit_OCR.setObjectName(_fromUtf8("edit_OCR"))
        self.horizontalLayout_6.addWidget(self.edit_OCR)
        self.gridLayout.addLayout(self.horizontalLayout_6, 8, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.button_done = QtGui.QPushButton(Form)
        self.button_done.setEnabled(False)
        self.button_done.setObjectName(_fromUtf8("button_done"))
        self.horizontalLayout_5.addWidget(self.button_done)
        self.button_cancel = QtGui.QPushButton(Form)
        self.button_cancel.setObjectName(_fromUtf8("button_cancel"))
        self.horizontalLayout_5.addWidget(self.button_cancel)
        self.gridLayout.addLayout(self.horizontalLayout_5, 12, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.edit_comment = QtGui.QLineEdit(Form)
        self.edit_comment.setObjectName(_fromUtf8("edit_comment"))
        self.horizontalLayout_8.addWidget(self.edit_comment)
        self.gridLayout.addLayout(self.horizontalLayout_8, 11, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.combo_measurementType = QtGui.QComboBox(Form)
        self.combo_measurementType.setEnabled(False)
        self.combo_measurementType.setObjectName(_fromUtf8("combo_measurementType"))
        self.horizontalLayout_4.addWidget(self.combo_measurementType)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.spin_port = QtGui.QSpinBox(Form)
        self.spin_port.setEnabled(False)
        self.spin_port.setMinimum(1)
        self.spin_port.setMaximum(4)
        self.spin_port.setObjectName(_fromUtf8("spin_port"))
        self.horizontalLayout_4.addWidget(self.spin_port)
        self.gridLayout.addLayout(self.horizontalLayout_4, 7, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.combo_name = QtGui.QComboBox(Form)
        self.combo_name.setObjectName(_fromUtf8("combo_name"))
        self.horizontalLayout.addWidget(self.combo_name)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_7.addWidget(self.label_8)
        self.edit_name = QtGui.QLineEdit(Form)
        self.edit_name.setObjectName(_fromUtf8("edit_name"))
        self.horizontalLayout_7.addWidget(self.edit_name)
        self.gridLayout.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.combo_classType = QtGui.QComboBox(Form)
        self.combo_classType.setObjectName(_fromUtf8("combo_classType"))
        self.horizontalLayout_2.addWidget(self.combo_classType)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.combo_instrumentType = QtGui.QComboBox(Form)
        self.combo_instrumentType.setObjectName(_fromUtf8("combo_instrumentType"))
        self.horizontalLayout_3.addWidget(self.combo_instrumentType)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.edit_address = QtGui.QLineEdit(Form)
        self.edit_address.setEnabled(False)
        self.edit_address.setObjectName(_fromUtf8("edit_address"))
        self.horizontalLayout_3.addWidget(self.edit_address)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_15 = QtGui.QLabel(Form)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_16.addWidget(self.label_15)
        self.edit_amplitude = QtGui.QLineEdit(Form)
        self.edit_amplitude.setEnabled(False)
        self.edit_amplitude.setObjectName(_fromUtf8("edit_amplitude"))
        self.horizontalLayout_16.addWidget(self.edit_amplitude)
        self.combo_amplitude = QtGui.QComboBox(Form)
        self.combo_amplitude.setEnabled(False)
        self.combo_amplitude.setObjectName(_fromUtf8("combo_amplitude"))
        self.combo_amplitude.addItem(_fromUtf8(""))
        self.combo_amplitude.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.combo_amplitude)
        self.gridLayout.addLayout(self.horizontalLayout_16, 10, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.button_cancel, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "GAS Edit", None))
        self.label_11.setText(_translate("Form", "Delay", None))
        self.combo_delay.setItemText(0, _translate("Form", "Seconds", None))
        self.label_13.setText(_translate("Form", "getCurrent", None))
        self.label_14.setText(_translate("Form", "getVoltage", None))
        self.label_12.setText(_translate("Form", "Delay 2 ", None))
        self.combo_delay_2.setItemText(0, _translate("Form", "Seconds", None))
        self.label_7.setText(_translate("Form", "OCR Calibration (A)", None))
        self.button_done.setText(_translate("Form", "Done", None))
        self.button_cancel.setText(_translate("Form", "Cancel", None))
        self.label_9.setText(_translate("Form", "Comment:", None))
        self.label_5.setText(_translate("Form", "Measurement Type", None))
        self.label_6.setText(_translate("Form", "Port", None))
        self.label.setText(_translate("Form", "Object to Edit", None))
        self.label_8.setText(_translate("Form", "Name", None))
        self.label_2.setText(_translate("Form", "Class Type", None))
        self.label_3.setText(_translate("Form", "Instrument Type", None))
        self.label_4.setText(_translate("Form", "Address", None))
        self.label_15.setText(_translate("Form", "Amplitude", None))
        self.combo_amplitude.setItemText(0, _translate("Form", "mV", None))
        self.combo_amplitude.setItemText(1, _translate("Form", "dBm", None))

